# -------- general ---------
user: "{{ ansible_user_id }}"
dotdir: "~/.config"

# ------- Alacritty --------
alacritty_dotdir: "{{ dotdir }}/alacritty"

# --------- FONTS ----------
fonts_dir: /usr/share/fonts
fonts_packages: [] # list of package names = Install fonts with package manager
fonts_download: [] # list of dict {"url": ..., "dest": ...} Download and install fonts

# ---------- ZSH -----------
zsh_dotdir: "{{ dotdir }}/zsh"
zsh_bin: "/usr/bin/zsh"
zsh_path: "/usr/share/zsh"
zsh_plugins: "{{ zsh_path }}/plugins" # Plugins path
zsh_plugins_repos: [] # Dict with zsh plugins { "repo": ..., "dest": ... } where dest is relative to the plugins path

zsh_settings: [] # { "src": ..., "dest": ...} simple file copy
zsh_template_settings: [] # jinja templates

# ---------- NVIM ----------
# nvim_checksum wget https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz.sha256sum --quiet -^C | awk '{print $1 }'
nvim_checksum: sha256:fa93f06bec111fea6f316f186b96e19ba289a2dca2d0731e23597398b7397c8f
nvim_url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
nvim_pip_executable: pip3
