---
- name: "zsh packages"
  community.general.pacman:
    name: "{{ zsh_packages }}"
    state: present
  become: true

- name: "zsh optional packages"
  include_tasks: install-optional.yml
  vars:
    optional_packages: "{{ zsh_optional_packages }}"

- name: "zsh config directory"
  file:
    path: "{{ zsh_dotdir }}"
    state: directory
    mode: '0755'

- name: "zsh dotfiles"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items: "{{ zsh_settings }}"

- name: "zsh dotfiles templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items: "{{ zsh_template_settings }}"

- name: "zsh as login shell"
  user:
    name: "{{ user }}"
    shell: "{{ zsh_bin }}"
  become: true
  when: zsh_login_shell | bool
