---
- name: "Neovim packages"
  community.general.pacman:
    name: "{{ nvim_packages }}"
    state: present
  become: true

- name: "Neovim config link"
  file:
    src: "{{ (playbook_dir ~ '/../../common/nvim') | realpath }}"
    dest: "{{ nvim_dotdir }}"
    state: link
