---
galaxy_info:
  author: Claudio F. Carneiro
  description: Configure a workstation with my dotfiles
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: ArchLinux
      versions:
        - all

dependencies: []
