alacritty_settings:
  - src: "{{ playbook_dir }}/../alacritty/alacritty.toml"
    dest: "{{ alacritty_dotdir }}/alacritty.toml"

kitty_settings:
  - src: "{{ playbook_dir }}/../kitty/kitty.conf"
    dest: "{{ kitty_dotdir }}/kitty.conf"

fastfetch_settings:
  - src: "{{ playbook_dir }}/../fastfetch/config.jsonc"
    dest: "{{ fastfetch_dotdir }}/config.jsonc"

zsh_settings:
  - src: zsh/p10k.zsh
    dest: "{{ zsh_path }}"

zsh_template_settings:
  - src: zsh/zshenv
    dest: "~/.zshenv"
  - src: zsh/zsh-config.j2 
    dest: "{{ zsh_path }}/zsh-config"
  - src: zsh/zsh-prompt.j2
    dest: "{{ zsh_path }}/zsh-prompt"
  - src: zsh/zshrc.j2
    dest: "{{ zsh_dotdir }}/.zshrc"

zsh_plugins_repos:
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "zsh-syntax-highlighting"
    - repo: https://github.com/zsh-users/zsh-history-substring-search.git
      dest: "zsh-history-substring-search"
    - repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "zsh-autosuggestions"
    - repo: https://github.com/romkatv/powerlevel10k.git
      dest: "zsh-theme-powerlevel10k"
