alacritty_settings:
  - src: "{{ playbook_dir }}/../alacritty/alacritty.toml"
    dest: "{{ alacritty_dotdir }}/alacritty.toml"

kitty_settings:
  - src: "{{ playbook_dir }}/../kitty/kitty.conf"
    dest: "{{ kitty_dotdir }}/kitty.conf"

fastfetch_settings:
  - src: "{{ playbook_dir }}/../fastfetch/config.jsonc"
    dest: "{{ fastfetch_dotdir }}/config.jsonc"

zsh_settings:
  - src: "{{ playbook_dir }}/../zsh/p10k.zsh"
    dest: "{{ zsh_dotdir }}/p10k.zsh"

zsh_template_settings:
  - src: "{{ playbook_dir }}/../zsh/zshenv"
    dest: "~/.zshenv"
  - src: "{{ playbook_dir }}/../zsh/zsh-config.j2"
    dest: "{{ zsh_dotdir }}/zsh-config"
  - src: "{{ playbook_dir }}/../zsh/zsh-prompt.j2"
    dest: "{{ zsh_dotdir }}/zsh-prompt"
  - src: "{{ playbook_dir }}/../zsh/zshrc.j2"
    dest: "{{ zsh_dotdir }}/.zshrc"
