---
- hosts: all
  become: false
  gather_facts: true
# connection: local

  vars:
    setup_zsh: true
    setup_fonts: false
    setup_nvim: false
    setup_alacritty: true

  roles:
    - setup-workstation
