-- WezTerm colors generated by matugen from the current wallpaper.
-- Source: linux/matugen/templates/wezterm.lua — do not edit the generated file.
-- stylua: ignore
return {
   foreground = '{{colors.on_surface.default.hex}}',
   background = '{{colors.surface.default.hex}}',
   cursor_bg = '{{colors.primary.default.hex}}',
   cursor_border = '{{colors.primary.default.hex}}',
   cursor_fg = '{{colors.on_primary.default.hex}}',
   selection_bg = '{{colors.primary_container.default.hex}}',
   selection_fg = '{{colors.on_primary_container.default.hex}}',
   ansi = {
      '{{colors.surface_container_highest.default.hex}}', -- black
      '{{colors.red.default.hex}}', -- red
      '{{colors.green.default.hex}}', -- green
      '{{colors.yellow.default.hex}}', -- yellow
      '{{colors.blue.default.hex}}', -- blue
      '{{colors.magenta.default.hex}}', -- magenta/purple
      '{{colors.cyan.default.hex}}', -- cyan
      '{{colors.on_surface_variant.default.hex}}', -- white
   },
   brights = {
      '{{colors.outline.default.hex}}', -- black
      '{{colors.on_red_container.default.hex}}', -- red
      '{{colors.on_green_container.default.hex}}', -- green
      '{{colors.on_yellow_container.default.hex}}', -- yellow
      '{{colors.on_blue_container.default.hex}}', -- blue
      '{{colors.on_magenta_container.default.hex}}', -- magenta/purple
      '{{colors.on_cyan_container.default.hex}}', -- cyan
      '{{colors.on_surface.default.hex}}', -- white
   },
   tab_bar = {
      background = 'rgba(0, 0, 0, 0.4)',
      active_tab = { bg_color = '{{colors.primary.default.hex}}', fg_color = '{{colors.on_primary.default.hex}}' },
      inactive_tab = { bg_color = '{{colors.surface_container.default.hex}}', fg_color = '{{colors.on_surface_variant.default.hex}}' },
      inactive_tab_hover = { bg_color = '{{colors.surface_container_high.default.hex}}', fg_color = '{{colors.on_surface.default.hex}}' },
      new_tab = { bg_color = '{{colors.surface.default.hex}}', fg_color = '{{colors.on_surface.default.hex}}' },
      new_tab_hover = { bg_color = '{{colors.surface_container_high.default.hex}}', fg_color = '{{colors.on_surface.default.hex}}', italic = true },
   },
   visual_bell = '{{colors.error.default.hex}}',
   scrollbar_thumb = '{{colors.outline_variant.default.hex}}',
   split = '{{colors.outline.default.hex}}',
   compose_cursor = '{{colors.tertiary.default.hex}}',
}
