require('carneirofc.plugins.setup-clang-format').setup()
require('carneirofc.plugins.setup-galaxyline').setup()
require('carneirofc.plugins.setup-mdformat').setup()
require('carneirofc.plugins.setup-nvim-tree').setup()
require('carneirofc.plugins.setup-telescope').setup()
require('carneirofc.plugins.setup-treesitter').setup()
require('carneirofc.plugins.setup-gitgutter').setup()
